### PR TITLE
fix build error for older versions of Xcode

### PR DESCRIPTION
**Pull request by justAnotherDev**
was getting an error when attempting to build using Xcode's 11.2.1 toolchain

```
Sources/swift-test-codecov/main.swift:34:113: error: type of expression is ambiguous without more context
        help: ArgumentHelp("The metric over which to aggregate. One of \(CodeCov.AggregateProperty.allCases.map(\.rawValue))")
                                                                                                                ^~~~~~~~~~
```

### CODE REVIEW

**Review by mattpolzin — APPROVED** [review]
Ah yes, may as well support Swift versions prior to 5.2 at such a low cost.

Thanks!

**Comment by mattpolzin** [comment]
Available in version 0.7.1. https://github.com/mattpolzin/swift-test-codecov/releases/tag/0.7.1
